import type { DomainScan } from '../../../shared/types';

export function createSampleScan(): DomainScan {
  const now = new Date();
  const createdAt = new Date(now.getTime() - 1000 * 60 * 5).toISOString(); // 5 minutes ago
  const expiresAt = new Date(now.getTime() + 1000 * 60 * 60 * 24).toISOString();

  return {
    scanId: 'sample-scan-demo-id',
    domain: 'perimeter-demo.io',
    createdAt,
    expiresAt,
    status: 'completed',
    score: 88,
    scoreLabel: 'External Hygiene Score',
    completeness: 'complete',
    completenessDetails: {
      completed: 6,
      total: 6,
      failed: [],
    },
    categories: {
      whois: {
        status: 'completed',
        data: {
          registrar: 'Cloudflare, Inc.',
          createdDate: '2021-03-15T00:00:00Z',
          expiresDate: '2027-03-15T00:00:00Z',
          nameservers: ['ns1.cloudflare.com', 'ns2.cloudflare.com'],
          dnssec: 'active',
        },
      },
      dns: {
        status: 'completed',
        data: {
          addresses: ['104.21.45.10', '172.67.180.22'],
          aaaa: ['2606:4700:3031::6815:2d0a'],
          mx: ['aspmx.l.google.com (10)', 'alt1.aspmx.l.google.com (20)'],
          ns: ['ns1.cloudflare.com', 'ns2.cloudflare.com'],
          txt: ['v=spf1 include:_spf.google.com ~all'],
          cname: [],
          spf: { present: true, policy: 'v=spf1 include:_spf.google.com ~all' },
          dmarc: { present: true, policy: 'none' },
          dnssec: { observed: false, note: 'DNSSEC status requires validating resolver' },
        },
      },
      subdomains: {
        status: 'completed',
        data: {
          available: true,
          total: 5,
          subdomains: [
            'api.perimeter-demo.io',
            'auth.perimeter-demo.io',
            'app.perimeter-demo.io',
            'vpn.perimeter-demo.io',
            'mail.perimeter-demo.io',
          ],
        },
      },
      tls: {
        status: 'completed',
        data: {
          available: true,
          subject: '{"CN":"perimeter-demo.io"}',
          issuer: '{"O":"Let\'s Encrypt","CN":"R3"}',
          protocol: 'TLSv1.3',
          validFrom: '2026-08-01T00:00:00Z',
          validTo: '2026-11-01T23:59:59Z',
          fingerprint256: '9B:4C:E3:FA:11:78:2A:44:D0:6B:19:35:88:51:7A:DE:63:F1:C8:42:07:93:33:14:8B:FE:09:91:AA:62:4D:15',
          serialNumber: '04a29c118e7e90c5',
          authorized: true,
          subjectAltNames: ['perimeter-demo.io', 'www.perimeter-demo.io', '*.perimeter-demo.io'],
        },
      },
      http: {
        status: 'completed',
        data: {
          httpAvailable: true,
          httpsAvailable: true,
          httpsEnforced: true,
          httpRedirectsToHttps: true,
          finalObservedUrl: 'https://perimeter-demo.io/',
          redirectChain: ['http://perimeter-demo.io/', 'https://perimeter-demo.io/'],
          https: {
            url: 'https://perimeter-demo.io/',
            status: 200,
            headers: {
              server: 'cloudflare',
              'content-type': 'text/html; charset=UTF-8',
              'x-frame-options': 'DENY',
              'x-content-type-options': 'nosniff',
              'referrer-policy': 'strict-origin-when-cross-origin',
            },
            body: '<!DOCTYPE html><html><head><title>Demo Perimeter Portal</title></head><body><h1>Welcome</h1></body></html>',
            redirectChain: ['https://perimeter-demo.io/'],
            server: 'cloudflare',
            poweredBy: null,
            contentType: 'text/html; charset=UTF-8',
            missingSecurityHeaders: ['strict-transport-security', 'content-security-policy'],
            presentSecurityHeaders: ['x-frame-options', 'x-content-type-options', 'referrer-policy'],
            technologyEvidence: [],
          },
          worryingHeaders: ['strict-transport-security', 'content-security-policy'],
        },
      },
      exposure: {
        status: 'completed',
        data: {
          robots: { available: true, status: 200, present: true },
          sitemap: { available: true, status: 200, present: true },
          securityTxt: { available: true, status: 200, present: true },
        },
      },
      scoring: {
        status: 'completed',
        data: {
          score: 88,
          formula: 'Observable configuration posture (TLS, HTTPS enforcement, certificates, security headers, and email authentication)',
        },
      },
    },
    assets: [
      {
        id: 'asset-domain-1',
        type: 'DOMAIN',
        value: 'perimeter-demo.io',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'User input', description: 'Validated scan target', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-subdomain-1',
        type: 'SUBDOMAIN',
        value: 'api.perimeter-demo.io',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'Certificate Transparency', description: 'Observed in public certificate record', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-subdomain-2',
        type: 'SUBDOMAIN',
        value: 'auth.perimeter-demo.io',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'Certificate Transparency', description: 'Observed in public certificate record', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-subdomain-3',
        type: 'SUBDOMAIN',
        value: 'app.perimeter-demo.io',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'Certificate Transparency', description: 'Observed in public certificate record', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-subdomain-4',
        type: 'SUBDOMAIN',
        value: 'vpn.perimeter-demo.io',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'Certificate Transparency', description: 'Observed in public certificate record', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-subdomain-5',
        type: 'SUBDOMAIN',
        value: 'mail.perimeter-demo.io',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'Certificate Transparency', description: 'Observed in public certificate record', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-ip-1',
        type: 'IP',
        value: '104.21.45.10',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'DNS A record', description: 'Observed IPv4 address', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-ip-2',
        type: 'IP',
        value: '172.67.180.22',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'DNS A record', description: 'Observed IPv4 address', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-ns-1',
        type: 'NAMESERVER',
        value: 'ns1.cloudflare.com',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'DNS NS record', description: 'Authoritative nameserver', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-ns-2',
        type: 'NAMESERVER',
        value: 'ns2.cloudflare.com',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'DNS NS record', description: 'Authoritative nameserver', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-mx-1',
        type: 'MAIL_SERVER',
        value: 'aspmx.l.google.com',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'DNS MX record', description: 'Primary mail exchanger (priority 10)', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-cert-1',
        type: 'CERTIFICATE',
        value: 'SHA256:9b4ce3fa11782a44d06b193588517ade63f1c842079333148bfe0991aa624d15',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        metadata: {
          fingerprint256: '9B:4C:E3:FA:11:78:2A:44:D0:6B:19:35:88:51:7A:DE:63:F1:C8:42:07:93:33:14:8B:FE:09:91:AA:62:4D:15',
          issuer: '{"O":"Let\'s Encrypt","CN":"R3"}',
          validFrom: '2026-08-01T00:00:00Z',
          validTo: '2026-11-01T23:59:59Z',
        },
        evidence: [{ source: 'TLS handshake', description: 'Observed active leaf certificate', confidence: 'high', observedAt: createdAt }],
      },
      {
        id: 'asset-asn-1',
        type: 'ASN',
        value: 'AS13335',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'IP intelligence', description: 'Observed BGP routing autonomous system', confidence: 'medium', observedAt: createdAt }],
      },
      {
        id: 'asset-org-1',
        type: 'ORGANIZATION',
        value: 'Cloudflare, Inc.',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        evidence: [{ source: 'IP intelligence', description: 'Observed network routing organization', confidence: 'medium', observedAt: createdAt }],
      },
      {
        id: 'asset-geo-1',
        type: 'GEOLOCATION',
        value: 'San Jose, United States',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        metadata: {
          country: 'United States',
          region: 'California',
          city: 'San Jose',
          latitude: 37.3382,
          longitude: -121.8863,
          accuracy: 'approximate',
        },
        evidence: [{ source: 'IP intelligence', description: 'Approximate network point of presence location', confidence: 'low', observedAt: createdAt }],
      },
      {
        id: 'asset-geo-2',
        type: 'GEOLOCATION',
        value: 'Frankfurt am Main, Germany',
        targetDomain: 'perimeter-demo.io',
        discoveredAt: createdAt,
        metadata: {
          country: 'Germany',
          region: 'Hesse',
          city: 'Frankfurt am Main',
          latitude: 50.1109,
          longitude: 8.6821,
          accuracy: 'approximate',
        },
        evidence: [{ source: 'IP intelligence', description: 'Approximate network point of presence location', confidence: 'low', observedAt: createdAt }],
      },
    ],
    relationships: [
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-ip-1',
        type: 'resolves_to',
        evidence: { source: 'DNS A record', description: 'Resolves to 104.21.45.10', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-ip-2',
        type: 'resolves_to',
        evidence: { source: 'DNS A record', description: 'Resolves to 172.67.180.22', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-ns-1',
        type: 'uses_nameserver',
        evidence: { source: 'DNS NS record', description: 'Delegated to ns1.cloudflare.com', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-ns-2',
        type: 'uses_nameserver',
        evidence: { source: 'DNS NS record', description: 'Delegated to ns2.cloudflare.com', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-mx-1',
        type: 'delivers_mail_to',
        evidence: { source: 'DNS MX record', description: 'Mail routed to aspmx.l.google.com', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-subdomain-1',
        type: 'issued_for',
        evidence: { source: 'Certificate Transparency', description: 'Subdomain discovered in CT logs', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-subdomain-2',
        type: 'issued_for',
        evidence: { source: 'Certificate Transparency', description: 'Subdomain discovered in CT logs', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-subdomain-3',
        type: 'issued_for',
        evidence: { source: 'Certificate Transparency', description: 'Subdomain discovered in CT logs', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-subdomain-4',
        type: 'issued_for',
        evidence: { source: 'Certificate Transparency', description: 'Subdomain discovered in CT logs', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-domain-1',
        toAssetId: 'asset-subdomain-5',
        type: 'issued_for',
        evidence: { source: 'Certificate Transparency', description: 'Subdomain discovered in CT logs', confidence: 'high', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-ip-1',
        toAssetId: 'asset-asn-1',
        type: 'belongs_to_asn',
        evidence: { source: 'IP intelligence', description: 'BGP announcement AS13335', confidence: 'medium', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-ip-1',
        toAssetId: 'asset-org-1',
        type: 'operated_by',
        evidence: { source: 'IP intelligence', description: 'Operated by Cloudflare, Inc.', confidence: 'medium', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-ip-1',
        toAssetId: 'asset-geo-1',
        type: 'located_approximately_at',
        evidence: { source: 'IP intelligence', description: 'Approximate datacenter POP', confidence: 'low', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-ip-2',
        toAssetId: 'asset-geo-2',
        type: 'located_approximately_at',
        evidence: { source: 'IP intelligence', description: 'Approximate datacenter POP', confidence: 'low', observedAt: createdAt },
      },
      {
        fromAssetId: 'asset-cert-1',
        toAssetId: 'asset-domain-1',
        type: 'issued_for',
        evidence: { source: 'TLS SAN', description: 'Certificate valid for perimeter-demo.io', confidence: 'high', observedAt: createdAt },
      },
    ],
    findings: [
      {
        id: 'finding-sample-hsts',
        title: 'Missing strict-transport-security response header',
        severity: 'low',
        kind: 'configuration_weakness',
        category: 'http',
        observationStatus: 'not_observed',
        description: 'The HTTPS response does not declare Strict-Transport-Security (HSTS).',
        whyItMatters: 'HSTS instructs modern web browsers to strictly communicate over secure HTTPS connections, preventing man-in-the-middle downgrade attacks (SSL stripping).',
        investigationSteps: [
          'Verify that all subdomains and HTTP traffic successfully resolve over HTTPS.',
          'Add "Strict-Transport-Security: max-age=31536000; includeSubDomains" to edge web server responses.',
        ],
        recommendation: 'Enable Strict-Transport-Security (HSTS) with a sensible max-age once HTTPS stability is confirmed.',
        evidence: [{ source: 'HTTPS response headers', description: 'strict-transport-security header not observed', confidence: 'high', observedAt: createdAt }],
        confidence: 'high',
      },
      {
        id: 'finding-sample-csp',
        title: 'Missing content-security-policy response header',
        severity: 'low',
        kind: 'configuration_weakness',
        category: 'http',
        observationStatus: 'not_observed',
        description: 'The HTTPS response does not declare a Content-Security-Policy (CSP) header.',
        whyItMatters: 'Content-Security-Policy restricts scripts, styles, and frames the browser is allowed to execute, providing deep defense against Cross-Site Scripting (XSS).',
        investigationSteps: [
          'Audit third-party scripts and analytics dependencies loaded by the web application.',
          'Deploy a Content-Security-Policy-Report-Only header first to test for policy violations before enforcing.',
        ],
        recommendation: 'Define a Content-Security-Policy that restricts script origins and object loading.',
        evidence: [{ source: 'HTTPS response headers', description: 'content-security-policy header not observed', confidence: 'high', observedAt: createdAt }],
        confidence: 'high',
      },
      {
        id: 'finding-sample-dmarc',
        title: 'DMARC policy is in monitoring mode (p=none)',
        severity: 'low',
        kind: 'recommendation',
        category: 'dns',
        observationStatus: 'observed',
        description: 'A DMARC TXT record was observed with policy "p=none".',
        whyItMatters: 'While p=none enables aggregate reporting, it does not instruct receiving mail servers to reject or quarantine unauthorized emails that fail authentication.',
        investigationSteps: [
          'Review aggregate DMARC reports (rua reports) to ensure all legitimate mail sources pass SPF/DKIM.',
          'Gradually update policy from p=none to p=quarantine and eventually p=reject.',
        ],
        recommendation: 'Advance DMARC policy from monitoring (p=none) to quarantine or reject once mail flow is validated.',
        evidence: [{ source: 'DNS TXT lookup', description: 'Observed policy p=none at _dmarc.perimeter-demo.io', confidence: 'high', observedAt: createdAt }],
        confidence: 'high',
      },
    ],
    warnings: [],
  };
}
